label OpenWrt
  kernel /kernel.img
  fdt /sunxi.dtb
  append earlyprintk=sunxi-uart,0x02600000 mac_addr=b2:27:e1:c8:92:0c mac_addr1=b2:27:e1:c8:92:0d clk_ignore_unused initcall_debug=0 console=ttyAS0,115200 loglevel=8 root=/dev/mmcblk0p2 rootwait init=/sbin/init
