# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2022 OpenWrt.org

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for v2rayA
LUCI_DEPENDS:=+v2raya
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
